// tests/HardlineProphet.Tests/Infrastructure/Persistence/JsonGameStateRepositoryTests/SaveTests.cs
using HardlineProphet.Core; // GameConstants
using HardlineProphet.Core.Models;
using HardlineProphet.Infrastructure.Persistence;
// using HardlineProphet.Tests.Helpers; // Using base class now
using NFluent;
using System;
using System.Collections.Generic; // Added
using System.IO;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using Xunit;
using Xunit.Abstractions;

namespace HardlineProphet.Tests.Infrastructure.Persistence.JsonGameStateRepositoryTests;

// Inherit from the base class
public class SaveTests : PersistenceTestsBase
{
    // Constructor passes ITestOutputHelper to the base class
    public SaveTests(ITestOutputHelper output) : base(output) { }

    // Helper methods are inherited

    [Fact]
    public async Task SaveStateAsync_ShouldSerializeStateAndWriteToFile()
    {
        // Arrange
        var username = "SavingPlayer";
        var testDir = GetTestDirectoryPath(); // Use inherited helper
        // Create repo in non-dev mode for this test
        var repository = new JsonGameStateRepository(basePath: testDir, isDevMode: false);

        var stateToSave = new GameState
        { /* ... state setup ... */
            Username = username,
            Level = 10,
            Experience = 9999.9,
            Credits = 12345,
            Stats = new PlayerStats { HackSpeed = 15, Stealth = 12, DataYield = 5 }, // Use PlayerStats class
            ActiveMissionIds = new List<string> { "mission_save_test" },
            UnlockedPerkIds = new List<string> { "perk_save_test" },
            Version = GameConstants.CurrentSaveVersion,
            IsDevSave = false
        };

        var expectedFilePath = GetSaveFilePath(username); // Use inherited helper
        if (File.Exists(expectedFilePath)) { File.Delete(expectedFilePath); }

        Exception caughtException = null!;
        GameState deserializedState = null!;
        try
        {
            // Act
            _output.WriteLine($"Calling SaveStateAsync for user: {username}");
            await repository.SaveStateAsync(stateToSave);
            _output.WriteLine($"SaveStateAsync completed.");

            // Assert (Reading back the file)
            _output.WriteLine($"Checking if file exists at: {expectedFilePath}");
            Check.That(File.Exists(expectedFilePath)).IsTrue();
            _output.WriteLine($"File exists check passed.");

            var json = await File.ReadAllTextAsync(expectedFilePath);
            _output.WriteLine($"Read back JSON:\n{json}");
            // Use options consistent with loading
            deserializedState = JsonSerializer.Deserialize<GameState>(json, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
            _output.WriteLine($"Deserialized state successfully.");

        }
        catch (Exception ex) { caughtException = ex; _output.WriteLine($"!!! Exception caught: {ex.GetType().Name} - {ex.Message}\n{ex.StackTrace}"); }
        // Cleanup handled by base class Dispose

        // Assert (Checking the content)
        Check.That(caughtException).IsNull(); // Should be no exception during save/load
        Check.That(deserializedState).IsNotNull();

        // Assert: Detailed property checks
        Check.That(deserializedState.Username).IsEqualTo(stateToSave.Username);
        Check.That(deserializedState.Level).IsEqualTo(stateToSave.Level);
        Check.That(deserializedState.Experience).IsEqualTo(stateToSave.Experience);
        Check.That(deserializedState.Credits).IsEqualTo(stateToSave.Credits);
        Check.That(deserializedState.Stats).IsNotNull();
        // --- Check Stats Properties Individually --- Corrected
        Check.That(deserializedState.Stats.HackSpeed).IsEqualTo(stateToSave.Stats.HackSpeed);
        Check.That(deserializedState.Stats.Stealth).IsEqualTo(stateToSave.Stats.Stealth);
        Check.That(deserializedState.Stats.DataYield).IsEqualTo(stateToSave.Stats.DataYield);
        // -----------------------------------------
        Check.That(deserializedState.ActiveMissionIds).ContainsExactly(stateToSave.ActiveMissionIds);
        Check.That(deserializedState.UnlockedPerkIds).ContainsExactly(stateToSave.UnlockedPerkIds);
        Check.That(deserializedState.Version).IsEqualTo(stateToSave.Version);
        Check.That(deserializedState.IsDevSave).IsEqualTo(stateToSave.IsDevSave);
        // Checksum is generated by SaveStateAsync, so it should NOT be null here
        Check.That(deserializedState.Checksum).IsNotNull().And.IsNotEmpty();
    }

    [Fact]
    public async Task SaveStateAsync_ShouldCalculateAndStoreChecksum()
    {
        // Arrange
        var username = "ChecksumPlayer";
        var testDir = GetTestDirectoryPath(); // Use inherited helper
        var repository = new JsonGameStateRepository(basePath: testDir, isDevMode: false);
        var stateToSave = new GameState
        { /* ... state setup ... */
            Username = username,
            Level = 3,
            Experience = 100.0,
            Credits = 50,
            Stats = new PlayerStats { HackSpeed = 6, Stealth = 7, DataYield = 1 },
            Version = GameConstants.CurrentSaveVersion,
            IsDevSave = false
        };
        var expectedFilePath = GetSaveFilePath(username); // Use inherited helper
        if (File.Exists(expectedFilePath)) { File.Delete(expectedFilePath); }

        string expectedChecksum = ComputeExpectedChecksum(stateToSave); // Use inherited helper
        _output.WriteLine($"Calculated expected checksum: {expectedChecksum}");

        GameState deserializedState = null!;
        // Act
        await repository.SaveStateAsync(stateToSave);

        // Assert (Read back)
        Check.That(File.Exists(expectedFilePath)).IsTrue();
        var savedJson = await File.ReadAllTextAsync(expectedFilePath);
        _output.WriteLine($"Actual saved JSON:\n{savedJson}");
        deserializedState = JsonSerializer.Deserialize<GameState>(savedJson, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
        // Cleanup handled by base class Dispose

        // Assert (Checksum)
        Check.That(deserializedState).IsNotNull();
        Check.That(deserializedState.Checksum).IsNotNull().And.IsNotEmpty();
        Check.That(deserializedState.Checksum).IsEqualTo(expectedChecksum);
        Check.That(deserializedState.Username).IsEqualTo(stateToSave.Username);
        Check.That(deserializedState.Level).IsEqualTo(stateToSave.Level);
    }
}
